import { PrismaClient } from "@scout-for-lol/backend/generated/prisma/client/index.js";

/**
 * Path to the pre-generated template database.
 * This template is generated by `bun run generate:test-template` as part of the generate script.
 */
const TEMPLATE_DB_PATH = `${import.meta.dir}/template.db`;

/**
 * Creates an isolated test database and returns a PrismaClient instance configured to use it.
 *
 * Instead of running `prisma db push` for each test (which is slow and can trigger Bun segfaults),
 * this copies a pre-generated template database. This is much faster (~1ms vs ~500ms+).
 *
 * @param testName - A unique name for this test suite (used in the temp directory name)
 * @returns An object containing the PrismaClient instance and the database path
 */
export function createTestDatabase(testName: string): {
  prisma: PrismaClient;
  dbPath: string;
  dbUrl: string;
} {
  // Verify template exists (using shell test -f for sync check at module load time)
  const checkResult = Bun.spawnSync(["test", "-f", TEMPLATE_DB_PATH]);
  if (checkResult.exitCode !== 0) {
    throw new Error(
      `Test template database not found at ${TEMPLATE_DB_PATH}. ` + `Run 'bun run generate' to create it.`,
    );
  }

  // Create a unique test directory
  const tmpDir = Bun.env["TMPDIR"] ?? "/tmp";
  const testDir = `${tmpDir}/${testName}-${Date.now().toString()}-${Math.random().toString(36).slice(2)}`;
  Bun.spawnSync(["mkdir", "-p", testDir]);

  const testDbPath = `${testDir}/test.db`;
  const testDbUrl = `file:${testDbPath}`;

  // Copy the template database (fast!)
  Bun.spawnSync(["cp", TEMPLATE_DB_PATH, testDbPath]);

  const prisma = new PrismaClient({
    datasources: {
      db: {
        url: testDbUrl,
      },
    },
  });

  return {
    prisma,
    dbPath: testDbPath,
    dbUrl: testDbUrl,
  };
}

/**
 * Helper function to safely delete from tables that might not exist.
 * Useful in beforeEach/afterEach hooks for cleanup.
 *
 * @param fn - A function that returns a Promise (e.g., prisma.table.deleteMany())
 */
export async function deleteIfExists(fn: () => Promise<unknown>): Promise<void> {
  try {
    await fn();
  } catch {
    // Table might not exist, ignore
  }
}
