/**
 * Mapping from prismatic item IDs to their icon filenames.
 * Auto-generated by download script.
 */

export const prismaticItemIconMap: Record<number, string> = {
  443054: "443054.png",
  443055: "443055.png",
  443056: "443056.png",
  443058: "443058.png",
  443059: "443059.png",
  443060: "443060.png",
  443061: "443061.png",
  443064: "443064.png",
  443069: "443069.png",
  443079: "443079.png",
  443080: "443080.png",
  443081: "443081.png",
  443083: "443083.png",
  443090: "443090.png",
  443193: "443193.png",
  444636: "444636.png",
  444637: "444637.png",
  444644: "444644.png",
  446632: "446632.png",
  446656: "446656.png",
  446667: "446667.png",
  446671: "446671.png",
  446691: "446691.png",
  447100: "447100.png",
  447103: "447103.png",
  447104: "447104.png",
  447105: "447105.png",
  447106: "447106.png",
  447107: "447107.png",
  447108: "447108.png",
  447109: "447109.png",
  447110: "447110.png",
  447112: "447112.png",
  447115: "447115.png",
  447118: "447118.png",
  447119: "447119.png",
  447120: "447120.png",
  447121: "447121.png",
  447122: "447122.png",
  447123: "447123.png",
};

export function getPrismaticItemIconFilename(itemId: number): string | null {
  return prismaticItemIconMap[itemId] ?? null;
}
