name: Update after Renovate

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update-deno-lockfile:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Generate files
        run: cd packages/backend && ./src/database/generate.ts
      - name: Check if packages/backend/deno.json, packages/data/deno.json, or packages/report/deno.json has changed
        id: check_changed_files
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -qE 'packages/backend/deno.json|packages/data/deno.json|packages/report/deno.json'; then echo "file_changed=true" >> $GITHUB_ENV; else echo "file_changed=false" >> $GITHUB_ENV; fi
      - name: Update backend Deno lockfile
        if: env.file_changed == 'true'
        run: cd packages/backend/ && rm deno.lock && deno install && deno check src/index.ts
      - name: Update data Deno lockfile
        if: env.file_changed == 'true'
        run: cd packages/data/ && rm deno.lock && deno install && deno check src/index.ts
      - name: Update report Deno lockfile
        if: env.file_changed == 'true'
        run: cd packages/report/ && rm deno.lock && mv package.json package_cp.json && deno install && mv package_cp.json package.json && deno check src/index.ts
      - name: Commit and push changes
        if: env.file_changed == 'true'
        run: |
          git config --global user.name 'renovate-update'
          git config --global user.email 'github@sjer.red'
          git add .
          git commit --amend --no-edit
          git push --force
